name: Linux build

on:
  push:
  workflow_dispatch:

jobs:
  linux:
    name: Build for linux images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push
        shell: bash
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
          ./upload.sh
