name: Linux build

on:
  push:
  workflow_dispatch:
    inputs:
      override:
        description: "overrides build"
        required: false
        default: ""

jobs:
  linux:
    name: Build for linux images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push
        shell: bash
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" "ghcr.io" --password-stdin
          export "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          if [ -z "${{ github.event.inputs.override }}" ]; then
            python ./upload.py
          else
            python ./upload.py --override
          fi
          rm ~/.docker/config.json
